### ISSUE TITLE
less not compiled to css error on startup

### ISSUE THREAD

**Issue by Vad1mo** [groovydev/less-grails-plugin#8]
Hi, I have a website wich is based on bootstrap and bootswatch. http://bootswatch.com/spacelab/ 

``` css
filename:demo.less

@import "bootstrap.less"; // removed in grails
@import "responsive.less"; // removed in grails 
@import "variables.less";
@import "bootswatch.less";
@import "datepicker.less";
```

Creating a css file with http://git.io/recess works fine and I get the CSS where everything is compiled fine.

As the next step I ported everything to grails and this is where the problems begin.

Here is my configuration. In the demo.less file I removed the first two lines as they are already imported in the depends.

``` groovy
/hcp/grails-app/conf/ApplicationResources.groovy

modules = {
    application {
        resource url:'js/application.js'
    }
    my_style {
        dependsOn 'bootstrap'
        resource url:'less/demo.less', attrs:[rel: "stylesheet/less", type:'css']
                resource url:'css/hcp-custom.css', attrs:[media:'screen, projection']
    }
} 
```

here is the error I get when the application starts.

``` log
2013-01-09 22:10:50,643 [localhost-startStop-1] DEBUG twitterbootstrap.BootstrapResources  - dirLessSource: null
2013-01-09 22:10:50,645 [localhost-startStop-1] DEBUG twitterbootstrap.BootstrapResources  - dirTarget: null
2013-01-09 22:10:50,645 [localhost-startStop-1] DEBUG twitterbootstrap.BootstrapResources  - config: grails.plugins.twitterbootstrap.fixtaglib = [:]
2013-01-09 22:10:50,646 [localhost-startStop-1] DEBUG twitterbootstrap.BootstrapResources  - config: grails.plugins.twitterbootstrap.defaultBundle = bundle_bootstrap
2013-01-09 22:10:50,646 [localhost-startStop-1] DEBUG twitterbootstrap.BootstrapResources  - is lesscss-resources plugin loaded? true
2013-01-09 22:10:50,646 [localhost-startStop-1] DEBUG twitterbootstrap.BootstrapResources  - is jquery plugin loaded? true
| Error 2013-01-09 22:10:54,627 [localhost-startStop-1] ERROR resourceMappers.LessResourceMapper  - Error compiling less file: /Users/vad1mo/.grails/2.2.0/projects/hcp/tomcat/work/Tomcat/localhost/hcp/grails-resources/less/demo.less
Message: [object Object] (<script>#17742)
    Line | Method
->> 2690 | interpretLoop                 in org.mozilla.javascript.Interpreter
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   2487 | interpret                     in     ''
|    164 | call . . . . . . . . . . . .  in org.mozilla.javascript.InterpretedFunction
|    398 | doTopCall                     in org.mozilla.javascript.ContextFactory
|   3065 | doTopCall . . . . . . . . . . in org.mozilla.javascript.ScriptRuntime
|    175 | exec                          in org.mozilla.javascript.InterpretedFunction
|   1104 | evaluateString . . . . . . .  in org.mozilla.javascript.Context
|     42 | compile                       in com.groovydev.LessCompilerService
|     34 | map . . . . . . . . . . . . . in LessResourceMapper
|    139 | invoke                        in org.grails.plugin.resource.mapper.ResourceMapper
|    128 | invokeIfNotExcluded . . . . . in     ''
|    593 | applyMappers                  in org.grails.plugin.resource.ResourceProcessor
|    539 | prepareResource . . . . . . . in     ''
|    608 | doCall                        in org.grails.plugin.resource.ResourceProcessor$_prepareSingleDeclaredResource_closure12
|     29 | addDeclaredResource . . . . . in org.grails.plugin.resource.util.ResourceMetaStore
|    606 | prepareSingleDeclaredResource in org.grails.plugin.resource.ResourceProcessor
|    631 | doCall . . . . . . . . . . .  in org.grails.plugin.resource.ResourceProcessor$_prepareResourceBatch_closure14
|      8 | each                          in org.grails.plugin.resource.ResourceProcessorBatch
|    627 | prepareResourceBatch . . . .  in org.grails.plugin.resource.ResourceProcessor
|    810 | resourcesChanged              in     ''
|    806 | loadModules . . . . . . . . . in     ''
|   1075 | reloadAll                     in     ''
|    172 | doCall . . . . . . . . . . .  in ResourcesGrailsPlugin$_closure3
|    334 | innerRun                      in java.util.concurrent.FutureTask$Sync
|    166 | run . . . . . . . . . . . . . in java.util.concurrent.FutureTask
|   1110 | runWorker                     in java.util.concurrent.ThreadPoolExecutor
|    603 | run . . . . . . . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run                           in java.lang.Thread

2013-01-09 22:10:54,628 [localhost-startStop-1] ERROR StackTrace  - Full Stack Trace:
org.mozilla.javascript.JavaScriptException: [object Object] (<script>#17742)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:2690)
    at script(<script>:17742)
    at script(<script>:14732)
    at script(<script>:17735)
    at script(<script>:17749)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:2487)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:164)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
    at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:175)
    at org.mozilla.javascript.Context.evaluateString(Context.java:1104)
    at com.groovydev.LessCompilerService.compile(LessCompilerService.groovy:42)
    at LessResourceMapper.map(LessResourceMapper.groovy:34)
    at org.grails.plugin.resource.mapper.ResourceMapper.invoke(ResourceMapper.groovy:139)
    at org.grails.plugin.resource.mapper.ResourceMapper.invokeIfNotExcluded(ResourceMapper.groovy:128)
    at org.grails.plugin.resource.ResourceProcessor.applyMappers(ResourceProcessor.groovy:593)
    at org.grails.plugin.resource.ResourceProcessor.prepareResource(ResourceProcessor.groovy:539)
    at org.grails.plugin.resource.ResourceProcessor$_prepareSingleDeclaredResource_closure12.doCall(ResourceProcessor.groovy:608)
    at org.grails.plugin.resource.util.ResourceMetaStore.addDeclaredResource(ResourceMetaStore.groovy:29)
    at org.grails.plugin.resource.ResourceProcessor.prepareSingleDeclaredResource(ResourceProcessor.groovy:606)
    at org.grails.plugin.resource.ResourceProcessor$_prepareResourceBatch_closure14.doCall(ResourceProcessor.groovy:631)
    at org.grails.plugin.resource.ResourceProcessorBatch.each(ResourceProcessorBatch.groovy:8)
    at org.grails.plugin.resource.ResourceProcessor.prepareResourceBatch(ResourceProcessor.groovy:627)
    at org.grails.plugin.resource.ResourceProcessor.resourcesChanged(ResourceProcessor.groovy:810)
    at org.grails.plugin.resource.ResourceProcessor.loadModules(ResourceProcessor.groovy:806)
    at org.grails.plugin.resource.ResourceProcessor.reloadAll(ResourceProcessor.groovy:1075)
    at ResourcesGrailsPlugin$_closure3.doCall(ResourcesGrailsPlugin.groovy:172)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
```

If I take a look at the resulting website I see that the file is imported as demo.less and not as css. The hcp-custom.css is fine.  I tried different constellations like putting the content of the demo.less directly in resources groovy file. I tried different constellations but non of them seemed to work. I always get the same error on startup 

Does someone have an idea what this could be?

Im using grails 2.2.0

Cheers,

**Comment by Vad1mo** [comment]
maybe I found something. How I can make sure that all less files compiled together and not one after another?

**Comment by Vad1mo** [comment]
ok I got it, the problem occurs because the plugin compiles the less files one after each other.. but it need to compile them all together.

**Comment by rahulsom** [comment]
@Vad1mo How did you fix this?
